language: scala

env:
  - TRAVIS_JDK=8

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version

script: sbt ^test ^scripted

sudo: false

cache:
  directories:
    - "$HOME/.coursier/cache"
    - "$HOME/.ivy2/cache"
    - "$HOME/.jabba/jdk"

before_cache:
  # Delete the cached artifacts
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.sbt/sbt-js-engine
  - rm -rf $HOME/.coursier/cache/v*/http*/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine
  # Delete all ivydata files
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm

